feat(prompt-on-leave) - addition of prompt on leave
purecloudlabs/iframe-coordinator pull request #226
Opened 2023-02-10 09:45 UTC by gavin-everett-genesys

**Related Ticket :** https://inindca.atlassian.net/browse/COMUI-1289

2023-02-15 20:11 UTC, MattCheely commented on packages/iframe-coordinator/src/messages/PromptOnLeave.ts
> +  payload: boolean;
I would call this `shouldPrompt` or something else descriptive and update the doc comment to indicate that the host app will ask the user for confirmation before leaving the current page if it has received a message with the field set to true. 

I know I didn't capture this in the ticket, but after some research on the future of navigation APIs and what might be possible for us in the app, I'd also add an optional `message?: string` field documented as the message to prompt the user with (if possible).

2023-02-15 20:15 UTC, MattCheely requested changes
We should also update [client-setup.md](packages/iframe-coordinator/doc/client-setup.md) with a description of how to use `promptOnLeave` in the "Requesting Host Actions" section.  That will show up [here](https://apps.inindca.com/common-ui-docs/iframe-coordinator/modules/client.html) in the deployed docs.

2023-02-15 20:15 UTC, MattCheely commented on packages/iframe-coordinator/src/messages/PromptOnLeave.ts
> + * by the host application
I'd add some more detail to this to clarify how the message is intended to impact navigation. These comments are used in the [generated documentation](https://apps.inindca.com/common-ui-docs/iframe-coordinator/interfaces/client.NavRequest.html)

2023-02-22 13:19 UTC, MattCheely requested changes
Sorry for not catching it in the first round of reviews, but we should add some basic tests in `ClientToHost.spec.ts` for validation of the new message type.

2023-02-23 13:09 UTC, jordanstith15 approved these changes

2023-03-01 09:25 UTC, merged