fix: allowing routes with more specificity
purecloudlabs/iframe-coordinator pull request #270
Opened 2024-06-24 12:35 UTC by jordanstith15

2024-06-24 12:36 UTC, jordanstith15 commented on apps/ifc-example-client/ifc-cli.config.js
> +      },
Added extra app to test the client id and routes with more specificity

2024-06-24 12:36 UTC, jordanstith15 commented on packages/iframe-coordinator-cli/src/views/IframeEmbed.vue
> +      <span class="client-id">{{ currentClientId }}</span>
showing current client id so it's easier to see and test whether the correct client is loaded

2024-06-24 12:38 UTC, jordanstith15 commented on packages/iframe-coordinator/src/HostRouter.ts
> +    this._clients = Object.entries(clients)
Noticed that we were doing essentially Object.entries and doing brackets to get array data, which I've seen flagged before on code analyzers.

2024-06-24 12:38 UTC, jordanstith15 commented on packages/iframe-coordinator/src/HostRouter.ts
> +          b.assignedRoute.split("/").length - a.assignedRoute.split("/").length,
Sorts clients by number of url segments descending

2024-06-24 12:39 UTC, jordanstith15 commented on packages/iframe-coordinator/src/HostRouter.ts
> +    for (let client of this._clients) {
Noticed this issue as well.
It was continuing to loop after finding a matching client, causing it to seem like it was searching back to front.
Now it breaks the loop after finding a matching client and returns the first match.

2024-06-24 13:28 UTC, jordanstith15 commented on packages/iframe-coordinator/src/HostRouter.ts
> +          b.assignedRoute.split("/").length - a.assignedRoute.split("/").length,
No clue where the comma came from. I think the linter added it on commit

2024-07-02 07:01 UTC, MattCheely requested changes
We should add a new unit test against `getClientTarget` in `HostRoute.spec.ts` that would have failed previously but now succeeds.

2024-07-02 07:03 UTC, MattCheely commented
I think this has to be flagged as a breaking change because it can change which app shows in response to a specific URL. Technically it was a bug, but in theory there could be an app out there that accidentally relies on this behavior.

2024-07-17 08:16 UTC, MattCheely approved these changes

2024-07-17 09:40 UTC, merged